Repository hopeit-git/hopeit.engine, pull requests merged in 2021-05, with the labels that each got.

#48 feature(engine): Implementing Redis Stream Manager as a plugin
  .github/workflows/hopeit-engine-qa.yml
  Makefile
  apps/examples/simple-example/config/1x0.json
  apps/examples/simple-example/src/simple_example/service/something_generator.py
  docs/source/release-notes.rst
  engine/config/dev-docker.json
  engine/config/dev-local.json
  engine/config/dev-noauth.json
  engine/config/prod.json
  engine/src/hopeit/app/config.py
  engine/src/hopeit/server/config.py
  engine/src/hopeit/server/engine.py
  engine/src/hopeit/server/version.py
  engine/src/hopeit/streams/__init__.py
  engine/src/hopeit/streams/redis.py
  engine/test/integration/server/test_it_web.py
  engine/test/mock_app/__init__.py
  engine/test/mock_engine/__init__.py
  engine/test/unit/server/test_engine.py
  engine/test/unit/server/test_streams.py
Labels: 0.2.3

#58 fix(apps/plugins): Match app/plugins version with engine release
  .vscode/launch.json
  apps/benchmark/simple-benchmark/api/create_api_file.sh
  apps/benchmark/simple-benchmark/config/app-config-docker.json
  apps/benchmark/simple-benchmark/config/app-config.json
  apps/benchmark/simple-benchmark/docker/bench-engine/config/supervisord.conf
  apps/benchmark/simple-benchmark/test/benchmark-docker.sh
  apps/benchmark/simple-benchmark/test/start-local.sh
  apps/benchmark/simple-benchmark/test/warm-up-fs.sh
  apps/examples/simple-example/api/create-openapi-file.sh
  apps/examples/simple-example/api/openapi.json
  apps/examples/simple-example/config/app-config.json
  apps/examples/simple-example/test/integration/conftest.py
  apps/examples/simple-example/test/integration/test_it_collect_spawn.py
  apps/examples/simple-example/test/integration/test_it_download_something.py
  apps/examples/simple-example/test/integration/test_it_list_somethings.py
  apps/examples/simple-example/test/integration/test_it_query_concurrently.py
  apps/examples/simple-example/test/integration/test_it_query_something.py
  apps/examples/simple-example/test/integration/test_it_query_something_extended.py
  apps/examples/simple-example/test/integration/test_it_upload_something.py
  docker/engine/config/supervisord.conf
  docs/source/benchmark/dedicated.rst
  docs/source/quickstart/dev.rst
  engine/src/hopeit/server/version.py
  engine/test/unit/app/test_app_config.py
  plugins/auth/basic-auth/config/plugin-config.json
  plugins/auth/basic-auth/test/unit/__init__.py
Labels: 0.3.0, ready for review

#63 fix(simple-example): WARNING on OpenAPI schema generation, unify duplicate dataobjects
  apps/examples/simple-example/api/openapi.json
  apps/examples/simple-example/src/model/__init__.py
  apps/examples/simple-example/src/simple_example/collector/collect_spawn.py
  apps/examples/simple-example/src/simple_example/collector/query_concurrently.py
  apps/examples/simple-example/src/simple_example/shuffle/parallelize_event.py
  apps/examples/simple-example/src/simple_example/shuffle/spawn_event.py
  apps/examples/simple-example/src/simple_example/streams/process_events.py
  engine/src/hopeit/server/version.py
Labels: 0.3.0, ready for review

#64 fix(engine): remove dataobject validator feature from hopeit.engine.toolkit
  apps/examples/simple-example/api/openapi.json
  apps/examples/simple-example/src/model/__init__.py
  docs/source/apidocs/hopeit.toolkit.rst
  docs/source/release-notes.rst
  engine/src/hopeit/dataobjects/__init__.py
  engine/src/hopeit/dataobjects/validation.py
  engine/src/hopeit/server/version.py
  engine/src/hopeit/toolkit/__init__.py
  engine/src/hopeit/toolkit/validators.py
  engine/test/unit/dataobjects/test_validation.py
  engine/test/unit/toolkit/storage/__init__.py
  engine/test/unit/toolkit/test_validators.py
Labels: 0.3.0, ready for review

#66 fix(setup): Fix/aiohttp dependency
  docs/source/release-notes.rst
  engine/requirements.txt
  engine/setup.py
  engine/src/hopeit/app/context.py
  engine/src/hopeit/cli/openapi.py
  engine/src/hopeit/cli/server.py
  engine/src/hopeit/server/version.py
  engine/src/hopeit/server/web.py
Labels: 0.3.0, ready for review

#69 fix(engine)): Fix queue propagation on steps stage splits (SHUFFLE step)
  engine/src/hopeit/server/steps.py
  engine/test/unit/server/test_steps.py
Labels: 0.4.0, bug, dev-branch

#82 fix(apps-visualizer): missing template
  docs/source/release-notes.rst
  engine/src/hopeit/server/version.py
  plugins/ops/apps-visualizer/MANIFEST.in
Labels: 0.4.1

#79 fix(openapi): date and datetime types handled in query string parameters
  apps/examples/simple-example/src/simple_example/download_something.py
  apps/examples/simple-example/test/integration/test_it_download_something.py
  apps/examples/simple-example/test/integration/test_it_download_something_not_found.py
  docs/source/release-notes.rst
  engine/src/hopeit/app/api.py
  engine/src/hopeit/server/api.py
  engine/src/hopeit/server/version.py
  engine/test/mock_app/__init__.py
  engine/test/mock_app/mock_app_api_get_list.py
  engine/test/mock_app/mock_app_api_query_args.py
Labels: ready for review
